name: Issue Macro

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Issue Title"
        required: true
      body:
        description: "Issue Body"
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Issue
        uses: peter-evans/create-issue@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.inputs.title }}
          body: ${{ github.event.inputs.body }}
          labels: enhancement, automation
